# Generated by Django 5.0 on 2023-12-29 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nation', models.CharField(max_length=100)),
                ('league', models.CharField(max_length=100)),
                ('full_name', models.CharField(max_length=100)),
                ('short_name', models.CharField(max_length=50)),
                ('stadium', models.CharField(max_length=255)),
                ('logo', models.ImageField(upload_to='')),
            ],
        ),
    ]
