# Generated by Django 5.0 on 2024-01-01 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0003_playermatchstats_match_players'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='webcam',
            new_name='match',
        ),
    ]
