# Generated by Django 5.0 on 2024-01-03 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0004_rename_webcam_comment_match'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='players',
        ),
        migrations.DeleteModel(
            name='PlayerMatchStats',
        ),
    ]
