# Generated by Django 5.0.1 on 2024-01-06 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0005_remove_match_players_delete_playermatchstats'),
        ('player', '0002_remove_player_assists_remove_player_goals_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_ratings', to='match.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='player.player')),
            ],
            options={
                'unique_together': {('match', 'player')},
            },
        ),
    ]
