# Generated by Django 5.0 on 2024-01-03 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0002_remove_club_logo'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorite_teams',
            field=models.ManyToManyField(blank=True, related_name='fans', to='club.club'),
        ),
    ]
