# Generated by Django 5.0 on 2024-01-01 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='assists',
        ),
        migrations.RemoveField(
            model_name='player',
            name='goals',
        ),
        migrations.RemoveField(
            model_name='player',
            name='performances',
        ),
        migrations.RemoveField(
            model_name='player',
            name='red_card',
        ),
        migrations.RemoveField(
            model_name='player',
            name='yellow_card',
        ),
    ]
